name: Bug report
description: Create a report to help us improve
title: "fix: "
labels: ["type::bug", "status::backlog"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
  - type: textarea
    id: steps
    attributes:
      label: To Reproduce
      description: "Steps to reproduce the behavior:"
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: input
    id: device
    attributes:
      label: Device
      description: The device type your using to access the Buddy.
      placeholder: Desktop, Android, iPhone6...
  - type: input
    id: browser
    attributes:
      label: Browser
      description: The browser you used, preferably including the version.
      placeholder: e.g. stock browser, safari
